### ISSUE TITLE
GitHub Pages is not working

### ISSUE THREAD

**Issue by GaryHilares** [TechAxel/BugAir#1]
## Description
Entering the link that appears in GitHub pages gives an error and does not displays the game.

## Screenshot
![image](https://user-images.githubusercontent.com/46727048/112542830-08a20480-8d83-11eb-8ba6-601d58c5fba4.png)

## Platform
Chrome.

**Comment by TechAxel** [comment]
https://BugAir-6.techaxel.repl.co 
try this site, bug air (no edits) is on

**Comment by GaryHilares** [comment]
That works. Thanks!
